### ISSUE TITLE
catch2 discovery not working in vs2018 15.8.8

### ISSUE THREAD

**Issue by davidsanda** [JohnnyHendriks/TestAdapter_Catch2#13]
Simple tests, using catch2 adapter in visual studio 2017 enterprise v 15.8.8

[11/6/2018 1:21:30 AM Informational] ------ Discover test started ------
[11/6/2018 1:21:30 AM Error] Failed to load RunSettings file: 'C:\proj1\server-bin\ReferenceTests.runsettings'. Please check if the file exists and is valid.
[11/6/2018 1:21:30 AM Error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Microsoft.VisualStudio.TestWindow.Controller.Request.InitRunSettings(String settingsFile, IEnumerable`1 customSettingsImporters)
   at Microsoft.VisualStudio.TestWindow.Controller.Request.GenerateTestRunSettings(RunSettingConfigurationInfoState infoState)
   at Microsoft.VisualStudio.TestWindow.Controller.TestDiscoveryRequest.<CreateRequests>d__16.MoveNext()
   at Microsoft.VisualStudio.TestWindow.Controller.Request.<RunRequests>d__95.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestWindow.Controller.Request.<ProcessRequest>d__94.MoveNext()
[11/6/2018 1:21:30 AM Informational] ========== Discover test finished: 0 found (0:00:00.0562161) ==========

**Comment by JohnnyHendriks** [comment]
I've had no problems in VS2017 v15.8.8, so that's probably not the problem. The only possible cause I can see is that there is something wrong with the runsettings-file. Typically the runsettings-file doesn't need to make use of DTD as far as I know, so you could try to remove those elements if they are there. Maybe try with a minimal runsettings file (see [Settings](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Settings.md)) as a sanity check.

**Comment by snahmad** [comment]
I have same issue with VS2019

**Comment by JohnnyHendriks** [comment]
Just released a new version (1.6.0) and going through old issues. Not sure what to do with this issue so I'm closing it.
