### ISSUE TITLE
Exception: Input string was not in a correct format.

### ISSUE THREAD

**Issue by marzer** [JohnnyHendriks/TestAdapter_Catch2#39]
Hello,

I've had this issue occur randomly when adding a new `TEST_CASE()` to my code. It doesn't appear to matter what the case is named, or how many total tests are created by the project, but always at some point adding a new `TEST_CASE()` causes discovery to fail with this error message:

```
An exception occurred while test discoverer 'TestDiscoverer' was loading tests. Exception: Input string was not in a correct format.
```

After enabling trace-level diagnostics and scanning through the logfile, I found the stack trace of the exception:

```
TpTrace Error: 0 : 18696, 3, 2020/07/04, 19:04:27.884, 195695503626, testhost.exe, DiscovererEnumerator.DiscoverTestsFromSingleDiscoverer: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Catch2Interface.Discover.ListTests.MakeTestCaseLine(List`1 filenamelines)
   at Catch2Interface.Discover.ListTests.ProcessVerbose(String output, String source)
   at Catch2Interface.Discover.ListTests.ExtractTests(String output, String source)
   at Catch2Interface.Discoverer.ExtractTestCases(String source)
   at Catch2Interface.Discoverer.GetTests(IEnumerable`1 sources)
   at Catch2TestAdapter.TestDiscoverer.DiscoverTests(IEnumerable`1 sources)
   at Catch2TestAdapter.TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.DiscovererEnumerator.DiscoverTestsFromSingleDiscoverer(LazyExtension`2 discoverer, Dictionary`2 discovererToSourcesMap, DiscoveryContext context, TestCaseDiscoverySink discoverySink, IMessageLogger logger, Double& totalAdaptersUsed, Double& totalTimeTakenByAdapters) 
```

Pointing to this code:

https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/5c278a469a13749bae2e3e600254357f126bfcb0/Libraries/Catch2Interface/Discover/ListTests.cs#L253-L258

**Comment by marzer** [comment]
My .runsettings:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
   <!-- Configurations that affect the Test Framework -->
   <RunConfiguration>
       <MaxCpuCount>0</MaxCpuCount>
       <ResultsDirectory>..\build\TestResults</ResultsDirectory><!-- Path relative to solution directory -->
       <TestSessionTimeout>60000</TestSessionTimeout><!-- Milliseconds -->
   </RunConfiguration>

   <!-- Adapter Specific sections -->
   <Catch2Adapter>
	   <DiscoverCommandLine>--verbosity high --list-tests *</DiscoverCommandLine>
       <DiscoverTimeout>500</DiscoverTimeout><!-- Milliseconds -->
	   <FilenameFilter>(?i:test)</FilenameFilter>
       <WorkingDirectoryRoot>Solution</WorkingDirectoryRoot>
       <WorkingDirectory>..\tests\</WorkingDirectory>
	   <MessageFormat>AdditionalInfo</MessageFormat>
   </Catch2Adapter>

</RunSettings>

```

**Comment by marzer** [comment]
Ok, after adding some log spam and rebuilding the extension myself I've figured out why this is. It's because the regular expression used to isolate line numbers doesn't take thousands separators into account:
```cs
private static readonly Regex _rgxDefaultFilenameLineEnd = new Regex(@"(.*)\(([0-9]*)\)$");
```
So for input like `D:\Repositories\muu\tests\common.cpp(1,134)`, it fails to match. I'll submit a PR to fix this myself.

**Comment by JohnnyHendriks** [comment]
Thank you for catching, reporting and fixing this.
